"""
官方插件市场目录（种子数据 + 示例插件元数据）。
"""

from typing import Any

PLUGIN_CATALOG: list[dict[str, Any]] = [
    {
        "plugin_id": "feishu-integration",
        "name": "飞书集成",
        "description": "集成飞书 OA，支持发送消息、创建日程、审批等功能",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "🟢",
        "category": "office",
        "tags": ["办公", "OA", "飞书"],
        "permissions": ["network:outbound", "storage:read", "user:info"],
        "is_official": True,
        "is_featured": True,
        "signature": "official-feishu-v1-sha256-placeholder",
        "skills": ["send-message", "create-event", "get-approval"],
    },
    {
        "plugin_id": "wecom-integration",
        "name": "企业微信",
        "description": "企业微信消息推送与通讯录同步",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "💬",
        "category": "office",
        "tags": ["办公", "企业微信"],
        "permissions": ["network:outbound", "user:info"],
        "is_official": True,
        "is_featured": True,
        "signature": "official-wecom-v1-sha256-placeholder",
        "skills": ["send-wecom-message"],
    },
    {
        "plugin_id": "dingtalk-integration",
        "name": "钉钉集成",
        "description": "钉钉消息、审批与待办同步",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "📱",
        "category": "office",
        "tags": ["办公", "钉钉"],
        "permissions": ["network:outbound"],
        "is_official": True,
        "signature": "official-dingtalk-v1-sha256-placeholder",
        "skills": ["send-dingtalk-message"],
    },
    {
        "plugin_id": "weather-query",
        "name": "天气查询",
        "description": "查询全球城市实时天气与未来 7 天预报",
        "author": "平台官方",
        "version": "1.2.0",
        "icon": "🌤️",
        "category": "life",
        "tags": ["天气", "生活"],
        "permissions": ["network:outbound"],
        "is_official": True,
        "is_featured": True,
        "signature": "official-weather-v1-sha256-placeholder",
        "skills": ["weather-query"],
    },
    {
        "plugin_id": "email-sender",
        "name": "邮件发送",
        "description": "通过 SMTP 发送文本/HTML 邮件",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "📧",
        "category": "office",
        "tags": ["邮件", "通知"],
        "permissions": ["network:outbound"],
        "is_official": True,
        "signature": "official-email-v1-sha256-placeholder",
        "skills": ["send-email"],
    },
    {
        "plugin_id": "code-runner",
        "name": "代码执行",
        "description": "安全执行 Python/JavaScript 代码",
        "author": "平台官方",
        "version": "2.0.0",
        "icon": "💻",
        "category": "dev",
        "tags": ["代码", "开发"],
        "permissions": ["process:spawn", "filesystem:read"],
        "is_official": True,
        "is_featured": True,
        "signature": "official-code-v1-sha256-placeholder",
        "skills": ["run-code"],
    },
    {
        "plugin_id": "web-search",
        "name": "网络搜索",
        "description": "实时搜索互联网信息",
        "author": "平台官方",
        "version": "1.5.0",
        "icon": "🔍",
        "category": "data",
        "tags": ["搜索", "数据"],
        "permissions": ["network:outbound"],
        "is_official": True,
        "is_featured": True,
        "signature": "official-search-v1-sha256-placeholder",
        "skills": ["web-search"],
    },
    {
        "plugin_id": "salesforce-connector",
        "name": "Salesforce",
        "description": "Salesforce CRM 数据查询与同步",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "☁️",
        "category": "data",
        "tags": ["CRM", "Salesforce"],
        "permissions": ["network:outbound", "storage:read"],
        "is_official": True,
        "signature": "official-sf-v1-sha256-placeholder",
        "skills": ["sf-query-leads"],
    },
    {
        "plugin_id": "report-generator",
        "name": "报表生成",
        "description": "自动生成 Excel/PDF 业务报表",
        "author": "平台官方",
        "version": "1.1.0",
        "icon": "📊",
        "category": "industry",
        "tags": ["报表", "BI"],
        "permissions": ["filesystem:write", "storage:write"],
        "is_official": True,
        "signature": "official-report-v1-sha256-placeholder",
        "skills": ["generate-report"],
    },
    {
        "plugin_id": "hr-assistant",
        "name": "HR 助手",
        "description": "员工信息查询、请假审批辅助",
        "author": "平台官方",
        "version": "1.0.0",
        "icon": "👥",
        "category": "industry",
        "tags": ["HR", "人事"],
        "permissions": ["database:query", "user:info"],
        "is_official": True,
        "signature": "official-hr-v1-sha256-placeholder",
        "skills": ["query-employee", "submit-leave"],
    },
]
